name: CI to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare zero-ui
        id: prep_zero-ui
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/zero-ui
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push zero-ui
        id: docker_build_zero-ui
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/zero-ui/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep_zero-ui.outputs.tags }}

      - name: Build and push zerotier-controller
        id: docker_build_zerotier-controller
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/zerotier/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/zerotier-controller:latest
